general {
#lock_cmd = notify-send "Locking..." # Command to lock the session
#unlock_cmd = notify-send "Unlocked!" # Command to unlock the session
#before_sleep_cmd = notify-send "Going to sleep..." # Command before sleep
#after_sleep_cmd = notify-send "Waking up!" # Command after waking up
ignore_dbus_inhibit = false # Ignore DBus idle-inhibit requests
ignore_systemd_inhibit = false # Ignore systemd idle inhibitors
}

listener {
timeout = 600 # Idle timeout in seconds
on-timeout = hyprlock # Command when timeout occurs (e.g., lock screen)
#on-resume = notify-send "Welcome back!" # Command when activity resumes
}

