# /etc/rsyncd.conf


# This line is required by the /etc/init.d/rsyncd script
pid file = /run/rsyncd.pid
use chroot = yes
uid = root
gid = root
transfer logging = no
address = 192.168.1.2
log file = /var/log/rsyncd.log
hosts deny = *

[one]
max connections = 2
comment = rsync files service one
path = /rsyncd/one
secrets file = /etc/rsync.d/rsync.se
read only = no
write only = no
hosts allow = 192.168.1.2/28
list = no
# exclude = /example /test

