[one]
    comment = Samba for members user %u
    available = no
    browseable = no
    # 0750 mode for /smbd/one
    path = /smbd/one/%u
    writable = yes
    force directory mode = 0750
    force user = root
    force group = root
    valid users = 

[community]
    comment = Samba for community share
    available = no
    browseable = no
    # 4755 mode for /smbd/one
    path = /smbd/cloud/community/%u
    writable = yes
    force directory mode = 0750
    force user = root
    force group = root
    valid users = 

[public]
    comment = Public share 
    available = no
    guest ok = yes
    path = /smbd/public
    writable = yes
    valid users = 

