# user www-data or nginx or http for Linux dis
user nginx;
worker_processes auto;
worker_cpu_affinity auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

# Enables the use of JIT for regular expressions to speed-up their processing.
pcre_jit on;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	types_hash_max_size 4096;
	types_hash_bucket_size   128;
	server_tokens off; # Recommended practice is to turn this off

	server_names_hash_bucket_size 64;
	# server_name_in_redirect off;
	client_header_timeout 10m;
	client_body_timeout 10m;
	client_max_body_size 0;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	ignore_invalid_headers on;
	keepalive_timeout  60 35;
	send_timeout 10m;

	#connection_pool_size 512;
	request_pool_size 4k;
	client_header_buffer_size 2k;
	large_client_header_buffers 4 2k;

	output_buffers 1 32k;
	postpone_output 1460;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1.2 TLSv1.3; # Dropping SSLv3 (POODLE), TLS 1.0, 1.1
	ssl_prefer_server_ciphers off; # Don't force server cipher order.
	ssl_certificate  /etc/nginx/http.d/ssl.cert;
	ssl_certificate_key /etc/nginx/http.d/ssl.key;
	# Disable TLS session tickets (they are insecure). Default is 'on'.
	ssl_session_tickets off;

	##
	# Logging Settings
	##

	# Specifies the main log format.
	log_format main '$remote_addr - $remote_user [$time_local] "$request" '
		        '$status $body_bytes_sent "$http_referer" '
			'"$http_user_agent" "$http_x_forwarded_for"';
	# Sets the path, format, and configuration for a buffered log write.
	access_log /var/log/nginx/access.log main;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_vary on;
	gzip_proxied any;
	gzip_comp_level 6;
	gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;


	# Helper variable for proxying websockets.
	map $http_upgrade $connection_upgrade {
		default upgrade;
		'' close;
	}

	##
	# Virtual Host Configs
	##

	#include /etc/nginx/conf.d/*.conf;
	#include /etc/nginx/sites-enabled/*;
	include /etc/nginx/http.d/*.conf;
}

#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
#
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}
