#!/usr/sbin/nft -f
flush ruleset
# IPv4 Rules
# set default policy drop
table inet filter {
    chain input {
        type filter hook input priority filter;policy drop
        ct state vmap { established:accept, related:accept, invalid:drop } comment "Accept packets in established and related state, drop invalid packets"
    }
    chain output {
        type filter hook output priority filter;policy accept
        ct state vmap { new:accept, established:accept, related:accept, invalid:drop } comment "Accept packets in established and related state, drop invalid packets"
    }
    chain forward {
        type filter hook forward priority filter;policy accept
        ct state vmap { established:accept, related:accept, invalid:drop } comment "Accept packets in established and related state, drop invalid packets"
    }
}
# allow lo
add rule inet filter input iifname lo accept comment "Accept incoming localhost traffic"
add rule inet filter input oifname lo accept comment "Accept incoming localhost traffic"
# allow default ports out
define OUT_TCP_PORTS = { 80, 443, 873 } # http 80, https 443, rsync 873
define OUT_UDP_PORTS = { 53, 123 } # dns 53, ntp 123
add rule inet filter input tcp sport $OUT_TCP_PORTS accept
add rule inet filter input meta protocol ip udp sport $OUT_UDP_PORTS accept
# allow icmp out
add rule inet filter input icmp type echo-reply accept comment "Accept ping reply"

# IPv6 Rules
# set default policy drop
table ip6 filter {
    chain input {
        type filter hook input priority filter;policy drop
    }
    chain output {
        type filter hook output priority filter;policy drop
    }
    chain forward {
        type filter hook forward priority filter;policy drop
    }
}

# Include env rules
include "nftables.d/income.nft"
#include "nftables.d/pre_post.nft"
